name: Continuous Delivery

on:
  release:
    types: [ published ]

jobs: 
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Get the version
        if: ${{ github.event_name == 'release' }}
        id: version
        run: echo ::set-output name=VALUE::${GITHUB_REF##*/}

      - name: Build and Push
        if: ${{ github.event_name == 'release' }}
        uses: docker/build-push-action@v3
        with:
          push: true
          file: .Dockerfile
          tags: |
            ${{ secrets.REGISTRY_URL }}/chatgpt-bot:latest
            ${{ secrets.REGISTRY_URL }}/chatgpt-bot:${{ steps.version.outputs.VALUE }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache